#!/bin/bash
set -e
cat > openssl.cnf << EOF
[req]
req_extensions = v3_req
distinguished_name = req_distinguished_name
[req_distinguished_name]
[ v3_req ]
basicConstraints = CA:FALSE
keyUsage = nonRepudiation, digitalSignature, keyEncipherment
subjectAltName = @alt_names
[alt_names]
DNS.1 = kubernetes
DNS.2 = kubernetes.default
DNS.3 = kubernetes.default.svc
DNS.4 = kubernetes.default.svc.cluster.local
IP.1 = 10.3.0.1
IP.2 = 192.168.1.100
EOF
echo "Wrote master"
openssl genrsa -out ca-key.pem 2048
openssl req -x509 -new -nodes -key ca-key.pem -days 10000 -out ca.pem -subj "/CN=kube-ca"
openssl genrsa -out apiserver-key.pem 2048
openssl req -new -key apiserver-key.pem -out apiserver.csr -subj "/CN=kube-apiserver" -config openssl.cnf
openssl x509 -req -in apiserver.csr -CA ca.pem -CAkey ca-key.pem -CAcreateserial -out apiserver.pem -days 365 -extensions v3_req -extfile openssl.cnf
cat > worker-openssl.cnf << EOF
[req]
req_extensions = v3_req
distinguished_name = req_distinguished_name
[req_distinguished_name]
[ v3_req ]
basicConstraints = CA:FALSE
keyUsage = nonRepudiation, digitalSignature, keyEncipherment
subjectAltName = @alt_names
[alt_names]
IP.1 = 192.168.1.101
EOF
echo "Wrote worker1"
openssl genrsa -out CoreOS_2-worker-key.pem 2048
WORKER_IP=192.168.1.101 openssl req -new -key CoreOS_2-worker-key.pem -out CoreOS_2-worker.csr -subj "/CN=CoreOS_2" -config worker-openssl.cnf
WORKER_IP=192.168.1.101 openssl x509 -req -in CoreOS_2-worker.csr -CA ca.pem -CAkey ca-key.pem -CAcreateserial -out CoreOS_2-worker.pem -days 365 -extensions v3_req -extfile worker-openssl.cnf
rm worker-openssl.cnf
cat > worker-openssl.cnf << EOF
[req]
req_extensions = v3_req
distinguished_name = req_distinguished_name
[req_distinguished_name]
[ v3_req ]
basicConstraints = CA:FALSE
keyUsage = nonRepudiation, digitalSignature, keyEncipherment
subjectAltName = @alt_names
[alt_names]
IP.1 = 192.168.1.102
EOF
echo "Wrote worker2"
openssl genrsa -out CoreOS_3-worker-key.pem 2048
WORKER_IP=192.168.1.102 openssl req -new -key CoreOS_3-worker-key.pem -out CoreOS_3-worker.csr -subj "/CN=CoreOS_3" -config worker-openssl.cnf
WORKER_IP=192.168.1.102 openssl x509 -req -in CoreOS_3-worker.csr -CA ca.pem -CAkey ca-key.pem -CAcreateserial -out CoreOS_3-worker.pem -days 365 -extensions v3_req -extfile worker-openssl.cnf
mkdir -p /etc/kubernetes/ssl
cp ca.pem apiserver.pem apiserver-key.pem /etc/kubernetes/ssl
chmod 600 /etc/kubernetes/ssl/*-key.pem
chown root:root /etc/kubernetes/ssl/*-key.pem
echo "DONE"
