#!/bin/bash
set -e
cat > /etc/systemd/network/static.network << EOF
[Match]
Name=enp0s3

[Network]
Address=192.168.1.102/24
Gateway=192.168.1.1
DNS=192.168.1.1
EOF
echo "DONE, REBOOT AFTER 5"
sleep 5
reboot
